### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ghost** [ora600pl/awr_scripts#2]
C:\Installs\dbcli\cache\sppprd>awr_analyzer.py "C:\Installs\dbcli\cache\sppprd" awr_XYZ
Traceback (most recent call last):
  File "C:\Installs\dbcli\cache\sppprd\awr_analyzer.py", line 2299, in <module>
    aa.plot()
  File "C:\Installs\dbcli\cache\sppprd\awr_analyzer.py", line 2049, in plot
    fig['layout'].update(title='AWR ' + data_x[0] + " - " + data_x[-1] + " CPUs: " + str(self.cpu_count))
IndexError: list index out of range

**Comment by ghost** [comment]
Ignore.
